### PR TITLE
Remove call to var_dump

### PR DESCRIPTION
**Pull request by bcremer**
Remove call to `var_dump` that did not look intentional.

### CODE REVIEW

**Comment by Crell** [comment]
That is indeed a goof.  I was having trouble getting output in tests, so I must have missed it.  Thanks!

**Comment by reinfi** [comment]
Could you add a fix tag for that?

**Comment by Crell** [comment]
The 1.0.1 release is already out. 😄

**Comment by reinfi** [comment]
Not on packagist or somewhere else :-D 

composer update does not help.

**Comment by jdreesen** [comment]
There does not seem to be a tag either.

**Comment by reinfi** [comment]
now it is there, no idea why it was not visible for 2 days :-D

**Comment by Crell** [comment]
Because I was dumb and did `git push` instead of `git push --tags` until last night when I remembered. 🙃

**Pull request merged**
